### ISSUE TITLE
表单搜索问题

### ISSUE THREAD

**Issue by aim467** [zccbbg/wms-ruoyi#3]
仓库/库区/货架下的库区和货架列表的搜索存在同样的问题；
按用户的逻辑来说，所属仓库和所属库区这两个条件筛选，应该是搜索仓库和库区的名字进行模糊搜索吧，但是表单传入的确实 warehouseId 和 areaId，感觉有点奇怪

**Comment by zccbbg** [comment]
因为前端是select
